### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by dmax678** [labRadioVision/federated#1]
Do you have the code for tf 2.0

**Comment by labRadioVision** [comment]
Not yet, but it is under development. The code now works with tf 1.13. Thanks for you interest.

**Comment by labRadioVision** [comment]
Hello
to use the code with tensorflow >2 installed, please use the following workaround:

Replace:

import tensorflow as tf

with:

import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()

Please check also https://www.tensorflow.org/guide/migrate
