### ISSUE TITLE
tensorflow federated package

### ISSUE THREAD

**Issue by anupamme** [labRadioVision/federated#2]
Hello,

From my understanding of the code, it does not use the federated package from TensorFlow [1]. Is that something underworks? If not, I will be happy to take it up and send you a pull request.

1. https://github.com/tensorflow/federated

**Comment by labRadioVision** [comment]
Hello 
sure, it would be very useful. We can cooperate on this. 
Currently, the code does not use the FL package and we are not working on that (working on federated graph/network optimization). Some code clean up is also necessary.. but still underworks

Thanks
Stefano
