### ISSUE TITLE
datasets for training

### ISSUE THREAD

**Issue by anupamme** [labRadioVision/federated#3]
Hello

After looking at your code e.g. federated_sample_CNN_CFA.py, my understanding is that you use synthetic (programatically generated) data for training purposes. Is that correct?

If not, can you please point me to the data you are using?

I am interested in datasets from IoT space for ML so that's why the question.

**Comment by labRadioVision** [comment]
Hello 
the data comes from experiments inside an industrial pilot plant (so real data, not synthetic). 
Please check this pdf and descriptions in appendix:
https://arxiv.org/pdf/1912.13163.pdf

The link below should be also available for download:
Data Repository: “Federated Learning: example dataset (FMCW 122GHz radars),” IEEE Dataport, 2019. [Online]. Available: http://dx.doi.org/10.21227/8yqc-1j15.
